/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ExclusaoDeDadosRouteImport } from './routes/exclusao-de-dados'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AppAgentesRouteImport } from './routes/_app/agentes'
import { Route as AppAutoLikeRouteImport } from './routes/_app/auto-like'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppCommentToDmRouteImport } from './routes/_app/comment-to-dm'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppContatosRouteImport } from './routes/_app/contatos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppGatilhosRouteImport } from './routes/_app/gatilhos'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppIntegracoesRouteImport } from './routes/_app/integracoes'
import { Route as AppManualRouteImport } from './routes/_app/manual'
import { Route as AppOperacoesRouteImport } from './routes/_app/operacoes'
import { Route as AppPublicarRouteImport } from './routes/_app/publicar'
import { Route as AppReengajamentoRouteImport } from './routes/_app/reengajamento'
import { Route as AppSequenciasRouteImport } from './routes/_app/sequencias'
import { Route as AgendarSlugRouteImport } from './routes/agendar/$slug'
import { Route as ApiAutoLikeRouteImport } from './routes/api/auto-like'
import { Route as ApiAutomationsRouteImport } from './routes/api/automations'
import { Route as ApiCalendarRouteImport } from './routes/api/calendar'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ApiContactTagsRouteImport } from './routes/api/contact-tags'
import { Route as ApiContactsRouteImport } from './routes/api/contacts'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiDataDeletionRouteImport } from './routes/api/data-deletion'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as ApiReadyRouteImport } from './routes/api/ready'
import { Route as ApiSequencesRouteImport } from './routes/api/sequences'
import { Route as ApiTriggersRouteImport } from './routes/api/triggers'
import { Route as ApiWorkspacesRouteImport } from './routes/api/workspaces'
import { Route as ApiAiAgentsRouteImport } from './routes/api/ai/agents'
import { Route as ApiAiKnowledgeRouteImport } from './routes/api/ai/knowledge'
import { Route as ApiAiSettingsRouteImport } from './routes/api/ai/settings'
import { Route as ApiAiSuggestRouteImport } from './routes/api/ai/suggest'
import { Route as ApiAutomationsFlowIdRouteImport } from './routes/api/automations/$flowId'
import { Route as ApiAutomationsFieldsRouteImport } from './routes/api/automations/fields'
import { Route as ApiCalendarBookingPagesRouteImport } from './routes/api/calendar/booking-pages'
import { Route as ApiCalendarBookingsRouteImport } from './routes/api/calendar/bookings'
import { Route as ApiComplianceCheckRouteImport } from './routes/api/compliance/check'
import { Route as ApiContactsContactIdRouteImport } from './routes/api/contacts/$contactId'
import { Route as ApiContactsBulkRouteImport } from './routes/api/contacts/bulk'
import { Route as ApiMessagesSendRouteImport } from './routes/api/messages/send'
import { Route as ApiOperationsGoLiveRouteImport } from './routes/api/operations/go-live'
import { Route as ApiOperationsWebhooksRouteImport } from './routes/api/operations/webhooks'
import { Route as ApiPrivacyDeletionRequestsRouteImport } from './routes/api/privacy/deletion-requests'
import { Route as ApiPublicReviewsRouteImport } from './routes/api/public/reviews'
import { Route as ApiAutomationsFlowIdExecuteRouteImport } from './routes/api/automations/$flowId/execute'
import { Route as ApiAutomationsFlowIdSimulateRouteImport } from './routes/api/automations/$flowId/simulate'
import { Route as ApiContactsContactIdNotesRouteImport } from './routes/api/contacts/$contactId/notes'
import { Route as ApiIntegrationsGoogleCallbackRouteImport } from './routes/api/integrations/google/callback'
import { Route as ApiIntegrationsGoogleDisconnectRouteImport } from './routes/api/integrations/google/disconnect'
import { Route as ApiIntegrationsGoogleStartRouteImport } from './routes/api/integrations/google/start'
import { Route as ApiIntegrationsGoogleStatusRouteImport } from './routes/api/integrations/google/status'
import { Route as ApiIntegrationsGoogleSyncRouteImport } from './routes/api/integrations/google/sync'
import { Route as ApiIntegrationsMetaCallbackRouteImport } from './routes/api/integrations/meta/callback'
import { Route as ApiIntegrationsMetaDisconnectRouteImport } from './routes/api/integrations/meta/disconnect'
import { Route as ApiIntegrationsMetaMediaRouteImport } from './routes/api/integrations/meta/media'
import { Route as ApiIntegrationsMetaStartRouteImport } from './routes/api/integrations/meta/start'
import { Route as ApiIntegrationsMetaStatusRouteImport } from './routes/api/integrations/meta/status'
import { Route as ApiIntegrationsMetaValidateRouteImport } from './routes/api/integrations/meta/validate'
import { Route as ApiIntegrationsN8nConfigureRouteImport } from './routes/api/integrations/n8n/configure'
import { Route as ApiIntegrationsN8nDisconnectRouteImport } from './routes/api/integrations/n8n/disconnect'
import { Route as ApiIntegrationsN8nEventsRouteImport } from './routes/api/integrations/n8n/events'
import { Route as ApiIntegrationsN8nStatusRouteImport } from './routes/api/integrations/n8n/status'
import { Route as ApiIntegrationsN8nTestRouteImport } from './routes/api/integrations/n8n/test'
import { Route as ApiPublicBookingsSlugRouteImport } from './routes/api/public/bookings/$slug'
import { Route as ApiPublicWebhooksInstagramRouteImport } from './routes/api/public/webhooks/instagram'
import { Route as ApiPublicWebhooksWhatsappRouteImport } from './routes/api/public/webhooks/whatsapp'
import { Route as ApiIntegrationsMetaWhatsappCompleteRouteImport } from './routes/api/integrations/meta/whatsapp/complete'
import { Route as ApiIntegrationsMetaWhatsappDisconnectRouteImport } from './routes/api/integrations/meta/whatsapp/disconnect'
import { Route as ApiIntegrationsMetaWhatsappRegisterRouteImport } from './routes/api/integrations/meta/whatsapp/register'
import { Route as ApiIntegrationsMetaWhatsappTemplatesRouteImport } from './routes/api/integrations/meta/whatsapp/templates'
import { Route as ApiIntegrationsMetaWhatsappValidateRouteImport } from './routes/api/integrations/meta/whatsapp/validate'
import { Route as ApiPublicWebhooksN8nConnectionIdRouteImport } from './routes/api/public/webhooks/n8n/$connectionId'
import { Route as ApiIntegrationsMetaWhatsappMediaMediaIdRouteImport } from './routes/api/integrations/meta/whatsapp/media/$mediaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeDadosRoute = ExclusaoDeDadosRouteImport.update({
  id: '/exclusao-de-dados',
  path: '/exclusao-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentesRoute = AppAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AppRoute,
} as any)
const AppAutoLikeRoute = AppAutoLikeRouteImport.update({
  id: '/auto-like',
  path: '/auto-like',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppCommentToDmRoute = AppCommentToDmRouteImport.update({
  id: '/comment-to-dm',
  path: '/comment-to-dm',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGatilhosRoute = AppGatilhosRouteImport.update({
  id: '/gatilhos',
  path: '/gatilhos',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppManualRoute = AppManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AppRoute,
} as any)
const AppOperacoesRoute = AppOperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicarRoute = AppPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => AppRoute,
} as any)
const AppReengajamentoRoute = AppReengajamentoRouteImport.update({
  id: '/reengajamento',
  path: '/reengajamento',
  getParentRoute: () => AppRoute,
} as any)
const AppSequenciasRoute = AppSequenciasRouteImport.update({
  id: '/sequencias',
  path: '/sequencias',
  getParentRoute: () => AppRoute,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoLikeRoute = ApiAutoLikeRouteImport.update({
  id: '/api/auto-like',
  path: '/api/auto-like',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationsRoute = ApiAutomationsRouteImport.update({
  id: '/api/automations',
  path: '/api/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarRoute = ApiCalendarRouteImport.update({
  id: '/api/calendar',
  path: '/api/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactTagsRoute = ApiContactTagsRouteImport.update({
  id: '/api/contact-tags',
  path: '/api/contact-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsRoute = ApiContactsRouteImport.update({
  id: '/api/contacts',
  path: '/api/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataDeletionRoute = ApiDataDeletionRouteImport.update({
  id: '/api/data-deletion',
  path: '/api/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSequencesRoute = ApiSequencesRouteImport.update({
  id: '/api/sequences',
  path: '/api/sequences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTriggersRoute = ApiTriggersRouteImport.update({
  id: '/api/triggers',
  path: '/api/triggers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesRoute = ApiWorkspacesRouteImport.update({
  id: '/api/workspaces',
  path: '/api/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAgentsRoute = ApiAiAgentsRouteImport.update({
  id: '/api/ai/agents',
  path: '/api/ai/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiKnowledgeRoute = ApiAiKnowledgeRouteImport.update({
  id: '/api/ai/knowledge',
  path: '/api/ai/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSettingsRoute = ApiAiSettingsRouteImport.update({
  id: '/api/ai/settings',
  path: '/api/ai/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSuggestRoute = ApiAiSuggestRouteImport.update({
  id: '/api/ai/suggest',
  path: '/api/ai/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationsFlowIdRoute = ApiAutomationsFlowIdRouteImport.update({
  id: '/$flowId',
  path: '/$flowId',
  getParentRoute: () => ApiAutomationsRoute,
} as any)
const ApiAutomationsFieldsRoute = ApiAutomationsFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => ApiAutomationsRoute,
} as any)
const ApiCalendarBookingPagesRoute = ApiCalendarBookingPagesRouteImport.update({
  id: '/booking-pages',
  path: '/booking-pages',
  getParentRoute: () => ApiCalendarRoute,
} as any)
const ApiCalendarBookingsRoute = ApiCalendarBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ApiCalendarRoute,
} as any)
const ApiComplianceCheckRoute = ApiComplianceCheckRouteImport.update({
  id: '/api/compliance/check',
  path: '/api/compliance/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsContactIdRoute = ApiContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiContactsBulkRoute = ApiContactsBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiMessagesSendRoute = ApiMessagesSendRouteImport.update({
  id: '/api/messages/send',
  path: '/api/messages/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperationsGoLiveRoute = ApiOperationsGoLiveRouteImport.update({
  id: '/api/operations/go-live',
  path: '/api/operations/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperationsWebhooksRoute = ApiOperationsWebhooksRouteImport.update({
  id: '/api/operations/webhooks',
  path: '/api/operations/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivacyDeletionRequestsRoute =
  ApiPrivacyDeletionRequestsRouteImport.update({
    id: '/api/privacy/deletion-requests',
    path: '/api/privacy/deletion-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReviewsRoute = ApiPublicReviewsRouteImport.update({
  id: '/api/public/reviews',
  path: '/api/public/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationsFlowIdExecuteRoute =
  ApiAutomationsFlowIdExecuteRouteImport.update({
    id: '/execute',
    path: '/execute',
    getParentRoute: () => ApiAutomationsFlowIdRoute,
  } as any)
const ApiAutomationsFlowIdSimulateRoute =
  ApiAutomationsFlowIdSimulateRouteImport.update({
    id: '/simulate',
    path: '/simulate',
    getParentRoute: () => ApiAutomationsFlowIdRoute,
  } as any)
const ApiContactsContactIdNotesRoute =
  ApiContactsContactIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => ApiContactsContactIdRoute,
  } as any)
const ApiIntegrationsGoogleCallbackRoute =
  ApiIntegrationsGoogleCallbackRouteImport.update({
    id: '/api/integrations/google/callback',
    path: '/api/integrations/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleDisconnectRoute =
  ApiIntegrationsGoogleDisconnectRouteImport.update({
    id: '/api/integrations/google/disconnect',
    path: '/api/integrations/google/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleStartRoute =
  ApiIntegrationsGoogleStartRouteImport.update({
    id: '/api/integrations/google/start',
    path: '/api/integrations/google/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleStatusRoute =
  ApiIntegrationsGoogleStatusRouteImport.update({
    id: '/api/integrations/google/status',
    path: '/api/integrations/google/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSyncRoute =
  ApiIntegrationsGoogleSyncRouteImport.update({
    id: '/api/integrations/google/sync',
    path: '/api/integrations/google/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaCallbackRoute =
  ApiIntegrationsMetaCallbackRouteImport.update({
    id: '/api/integrations/meta/callback',
    path: '/api/integrations/meta/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaDisconnectRoute =
  ApiIntegrationsMetaDisconnectRouteImport.update({
    id: '/api/integrations/meta/disconnect',
    path: '/api/integrations/meta/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaMediaRoute =
  ApiIntegrationsMetaMediaRouteImport.update({
    id: '/api/integrations/meta/media',
    path: '/api/integrations/meta/media',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaStartRoute =
  ApiIntegrationsMetaStartRouteImport.update({
    id: '/api/integrations/meta/start',
    path: '/api/integrations/meta/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaStatusRoute =
  ApiIntegrationsMetaStatusRouteImport.update({
    id: '/api/integrations/meta/status',
    path: '/api/integrations/meta/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaValidateRoute =
  ApiIntegrationsMetaValidateRouteImport.update({
    id: '/api/integrations/meta/validate',
    path: '/api/integrations/meta/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsN8nConfigureRoute =
  ApiIntegrationsN8nConfigureRouteImport.update({
    id: '/api/integrations/n8n/configure',
    path: '/api/integrations/n8n/configure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsN8nDisconnectRoute =
  ApiIntegrationsN8nDisconnectRouteImport.update({
    id: '/api/integrations/n8n/disconnect',
    path: '/api/integrations/n8n/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsN8nEventsRoute =
  ApiIntegrationsN8nEventsRouteImport.update({
    id: '/api/integrations/n8n/events',
    path: '/api/integrations/n8n/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsN8nStatusRoute =
  ApiIntegrationsN8nStatusRouteImport.update({
    id: '/api/integrations/n8n/status',
    path: '/api/integrations/n8n/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsN8nTestRoute = ApiIntegrationsN8nTestRouteImport.update({
  id: '/api/integrations/n8n/test',
  path: '/api/integrations/n8n/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsSlugRoute = ApiPublicBookingsSlugRouteImport.update({
  id: '/api/public/bookings/$slug',
  path: '/api/public/bookings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksInstagramRoute =
  ApiPublicWebhooksInstagramRouteImport.update({
    id: '/api/public/webhooks/instagram',
    path: '/api/public/webhooks/instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksWhatsappRoute =
  ApiPublicWebhooksWhatsappRouteImport.update({
    id: '/api/public/webhooks/whatsapp',
    path: '/api/public/webhooks/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaWhatsappCompleteRoute =
  ApiIntegrationsMetaWhatsappCompleteRouteImport.update({
    id: '/api/integrations/meta/whatsapp/complete',
    path: '/api/integrations/meta/whatsapp/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaWhatsappDisconnectRoute =
  ApiIntegrationsMetaWhatsappDisconnectRouteImport.update({
    id: '/api/integrations/meta/whatsapp/disconnect',
    path: '/api/integrations/meta/whatsapp/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaWhatsappRegisterRoute =
  ApiIntegrationsMetaWhatsappRegisterRouteImport.update({
    id: '/api/integrations/meta/whatsapp/register',
    path: '/api/integrations/meta/whatsapp/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaWhatsappTemplatesRoute =
  ApiIntegrationsMetaWhatsappTemplatesRouteImport.update({
    id: '/api/integrations/meta/whatsapp/templates',
    path: '/api/integrations/meta/whatsapp/templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaWhatsappValidateRoute =
  ApiIntegrationsMetaWhatsappValidateRouteImport.update({
    id: '/api/integrations/meta/whatsapp/validate',
    path: '/api/integrations/meta/whatsapp/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksN8nConnectionIdRoute =
  ApiPublicWebhooksN8nConnectionIdRouteImport.update({
    id: '/api/public/webhooks/n8n/$connectionId',
    path: '/api/public/webhooks/n8n/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsMetaWhatsappMediaMediaIdRoute =
  ApiIntegrationsMetaWhatsappMediaMediaIdRouteImport.update({
    id: '/api/integrations/meta/whatsapp/media/$mediaId',
    path: '/api/integrations/meta/whatsapp/media/$mediaId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agentes': typeof AppAgentesRoute
  '/auto-like': typeof AppAutoLikeRoute
  '/calendario': typeof AppCalendarioRoute
  '/comment-to-dm': typeof AppCommentToDmRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/gatilhos': typeof AppGatilhosRoute
  '/inbox': typeof AppInboxRoute
  '/insights': typeof AppInsightsRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/manual': typeof AppManualRoute
  '/operacoes': typeof AppOperacoesRoute
  '/publicar': typeof AppPublicarRoute
  '/reengajamento': typeof AppReengajamentoRoute
  '/sequencias': typeof AppSequenciasRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/api/auto-like': typeof ApiAutoLikeRoute
  '/api/automations': typeof ApiAutomationsRouteWithChildren
  '/api/calendar': typeof ApiCalendarRouteWithChildren
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/contact-tags': typeof ApiContactTagsRoute
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/content': typeof ApiContentRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/data-deletion': typeof ApiDataDeletionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/sequences': typeof ApiSequencesRoute
  '/api/triggers': typeof ApiTriggersRoute
  '/api/workspaces': typeof ApiWorkspacesRoute
  '/api/ai/agents': typeof ApiAiAgentsRoute
  '/api/ai/knowledge': typeof ApiAiKnowledgeRoute
  '/api/ai/settings': typeof ApiAiSettingsRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/automations/$flowId': typeof ApiAutomationsFlowIdRouteWithChildren
  '/api/automations/fields': typeof ApiAutomationsFieldsRoute
  '/api/calendar/booking-pages': typeof ApiCalendarBookingPagesRoute
  '/api/calendar/bookings': typeof ApiCalendarBookingsRoute
  '/api/compliance/check': typeof ApiComplianceCheckRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRouteWithChildren
  '/api/contacts/bulk': typeof ApiContactsBulkRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/operations/go-live': typeof ApiOperationsGoLiveRoute
  '/api/operations/webhooks': typeof ApiOperationsWebhooksRoute
  '/api/privacy/deletion-requests': typeof ApiPrivacyDeletionRequestsRoute
  '/api/public/reviews': typeof ApiPublicReviewsRoute
  '/api/automations/$flowId/execute': typeof ApiAutomationsFlowIdExecuteRoute
  '/api/automations/$flowId/simulate': typeof ApiAutomationsFlowIdSimulateRoute
  '/api/contacts/$contactId/notes': typeof ApiContactsContactIdNotesRoute
  '/api/integrations/google/callback': typeof ApiIntegrationsGoogleCallbackRoute
  '/api/integrations/google/disconnect': typeof ApiIntegrationsGoogleDisconnectRoute
  '/api/integrations/google/start': typeof ApiIntegrationsGoogleStartRoute
  '/api/integrations/google/status': typeof ApiIntegrationsGoogleStatusRoute
  '/api/integrations/google/sync': typeof ApiIntegrationsGoogleSyncRoute
  '/api/integrations/meta/callback': typeof ApiIntegrationsMetaCallbackRoute
  '/api/integrations/meta/disconnect': typeof ApiIntegrationsMetaDisconnectRoute
  '/api/integrations/meta/media': typeof ApiIntegrationsMetaMediaRoute
  '/api/integrations/meta/start': typeof ApiIntegrationsMetaStartRoute
  '/api/integrations/meta/status': typeof ApiIntegrationsMetaStatusRoute
  '/api/integrations/meta/validate': typeof ApiIntegrationsMetaValidateRoute
  '/api/integrations/n8n/configure': typeof ApiIntegrationsN8nConfigureRoute
  '/api/integrations/n8n/disconnect': typeof ApiIntegrationsN8nDisconnectRoute
  '/api/integrations/n8n/events': typeof ApiIntegrationsN8nEventsRoute
  '/api/integrations/n8n/status': typeof ApiIntegrationsN8nStatusRoute
  '/api/integrations/n8n/test': typeof ApiIntegrationsN8nTestRoute
  '/api/public/bookings/$slug': typeof ApiPublicBookingsSlugRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/api/integrations/meta/whatsapp/complete': typeof ApiIntegrationsMetaWhatsappCompleteRoute
  '/api/integrations/meta/whatsapp/disconnect': typeof ApiIntegrationsMetaWhatsappDisconnectRoute
  '/api/integrations/meta/whatsapp/register': typeof ApiIntegrationsMetaWhatsappRegisterRoute
  '/api/integrations/meta/whatsapp/templates': typeof ApiIntegrationsMetaWhatsappTemplatesRoute
  '/api/integrations/meta/whatsapp/validate': typeof ApiIntegrationsMetaWhatsappValidateRoute
  '/api/public/webhooks/n8n/$connectionId': typeof ApiPublicWebhooksN8nConnectionIdRoute
  '/api/integrations/meta/whatsapp/media/$mediaId': typeof ApiIntegrationsMetaWhatsappMediaMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agentes': typeof AppAgentesRoute
  '/auto-like': typeof AppAutoLikeRoute
  '/calendario': typeof AppCalendarioRoute
  '/comment-to-dm': typeof AppCommentToDmRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/gatilhos': typeof AppGatilhosRoute
  '/inbox': typeof AppInboxRoute
  '/insights': typeof AppInsightsRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/manual': typeof AppManualRoute
  '/operacoes': typeof AppOperacoesRoute
  '/publicar': typeof AppPublicarRoute
  '/reengajamento': typeof AppReengajamentoRoute
  '/sequencias': typeof AppSequenciasRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/api/auto-like': typeof ApiAutoLikeRoute
  '/api/automations': typeof ApiAutomationsRouteWithChildren
  '/api/calendar': typeof ApiCalendarRouteWithChildren
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/contact-tags': typeof ApiContactTagsRoute
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/content': typeof ApiContentRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/data-deletion': typeof ApiDataDeletionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/sequences': typeof ApiSequencesRoute
  '/api/triggers': typeof ApiTriggersRoute
  '/api/workspaces': typeof ApiWorkspacesRoute
  '/api/ai/agents': typeof ApiAiAgentsRoute
  '/api/ai/knowledge': typeof ApiAiKnowledgeRoute
  '/api/ai/settings': typeof ApiAiSettingsRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/automations/$flowId': typeof ApiAutomationsFlowIdRouteWithChildren
  '/api/automations/fields': typeof ApiAutomationsFieldsRoute
  '/api/calendar/booking-pages': typeof ApiCalendarBookingPagesRoute
  '/api/calendar/bookings': typeof ApiCalendarBookingsRoute
  '/api/compliance/check': typeof ApiComplianceCheckRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRouteWithChildren
  '/api/contacts/bulk': typeof ApiContactsBulkRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/operations/go-live': typeof ApiOperationsGoLiveRoute
  '/api/operations/webhooks': typeof ApiOperationsWebhooksRoute
  '/api/privacy/deletion-requests': typeof ApiPrivacyDeletionRequestsRoute
  '/api/public/reviews': typeof ApiPublicReviewsRoute
  '/api/automations/$flowId/execute': typeof ApiAutomationsFlowIdExecuteRoute
  '/api/automations/$flowId/simulate': typeof ApiAutomationsFlowIdSimulateRoute
  '/api/contacts/$contactId/notes': typeof ApiContactsContactIdNotesRoute
  '/api/integrations/google/callback': typeof ApiIntegrationsGoogleCallbackRoute
  '/api/integrations/google/disconnect': typeof ApiIntegrationsGoogleDisconnectRoute
  '/api/integrations/google/start': typeof ApiIntegrationsGoogleStartRoute
  '/api/integrations/google/status': typeof ApiIntegrationsGoogleStatusRoute
  '/api/integrations/google/sync': typeof ApiIntegrationsGoogleSyncRoute
  '/api/integrations/meta/callback': typeof ApiIntegrationsMetaCallbackRoute
  '/api/integrations/meta/disconnect': typeof ApiIntegrationsMetaDisconnectRoute
  '/api/integrations/meta/media': typeof ApiIntegrationsMetaMediaRoute
  '/api/integrations/meta/start': typeof ApiIntegrationsMetaStartRoute
  '/api/integrations/meta/status': typeof ApiIntegrationsMetaStatusRoute
  '/api/integrations/meta/validate': typeof ApiIntegrationsMetaValidateRoute
  '/api/integrations/n8n/configure': typeof ApiIntegrationsN8nConfigureRoute
  '/api/integrations/n8n/disconnect': typeof ApiIntegrationsN8nDisconnectRoute
  '/api/integrations/n8n/events': typeof ApiIntegrationsN8nEventsRoute
  '/api/integrations/n8n/status': typeof ApiIntegrationsN8nStatusRoute
  '/api/integrations/n8n/test': typeof ApiIntegrationsN8nTestRoute
  '/api/public/bookings/$slug': typeof ApiPublicBookingsSlugRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/api/integrations/meta/whatsapp/complete': typeof ApiIntegrationsMetaWhatsappCompleteRoute
  '/api/integrations/meta/whatsapp/disconnect': typeof ApiIntegrationsMetaWhatsappDisconnectRoute
  '/api/integrations/meta/whatsapp/register': typeof ApiIntegrationsMetaWhatsappRegisterRoute
  '/api/integrations/meta/whatsapp/templates': typeof ApiIntegrationsMetaWhatsappTemplatesRoute
  '/api/integrations/meta/whatsapp/validate': typeof ApiIntegrationsMetaWhatsappValidateRoute
  '/api/public/webhooks/n8n/$connectionId': typeof ApiPublicWebhooksN8nConnectionIdRoute
  '/api/integrations/meta/whatsapp/media/$mediaId': typeof ApiIntegrationsMetaWhatsappMediaMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_app/agentes': typeof AppAgentesRoute
  '/_app/auto-like': typeof AppAutoLikeRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/comment-to-dm': typeof AppCommentToDmRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contatos': typeof AppContatosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gatilhos': typeof AppGatilhosRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/integracoes': typeof AppIntegracoesRoute
  '/_app/manual': typeof AppManualRoute
  '/_app/operacoes': typeof AppOperacoesRoute
  '/_app/publicar': typeof AppPublicarRoute
  '/_app/reengajamento': typeof AppReengajamentoRoute
  '/_app/sequencias': typeof AppSequenciasRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/api/auto-like': typeof ApiAutoLikeRoute
  '/api/automations': typeof ApiAutomationsRouteWithChildren
  '/api/calendar': typeof ApiCalendarRouteWithChildren
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/contact-tags': typeof ApiContactTagsRoute
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/content': typeof ApiContentRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/data-deletion': typeof ApiDataDeletionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/sequences': typeof ApiSequencesRoute
  '/api/triggers': typeof ApiTriggersRoute
  '/api/workspaces': typeof ApiWorkspacesRoute
  '/api/ai/agents': typeof ApiAiAgentsRoute
  '/api/ai/knowledge': typeof ApiAiKnowledgeRoute
  '/api/ai/settings': typeof ApiAiSettingsRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/automations/$flowId': typeof ApiAutomationsFlowIdRouteWithChildren
  '/api/automations/fields': typeof ApiAutomationsFieldsRoute
  '/api/calendar/booking-pages': typeof ApiCalendarBookingPagesRoute
  '/api/calendar/bookings': typeof ApiCalendarBookingsRoute
  '/api/compliance/check': typeof ApiComplianceCheckRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRouteWithChildren
  '/api/contacts/bulk': typeof ApiContactsBulkRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/operations/go-live': typeof ApiOperationsGoLiveRoute
  '/api/operations/webhooks': typeof ApiOperationsWebhooksRoute
  '/api/privacy/deletion-requests': typeof ApiPrivacyDeletionRequestsRoute
  '/api/public/reviews': typeof ApiPublicReviewsRoute
  '/api/automations/$flowId/execute': typeof ApiAutomationsFlowIdExecuteRoute
  '/api/automations/$flowId/simulate': typeof ApiAutomationsFlowIdSimulateRoute
  '/api/contacts/$contactId/notes': typeof ApiContactsContactIdNotesRoute
  '/api/integrations/google/callback': typeof ApiIntegrationsGoogleCallbackRoute
  '/api/integrations/google/disconnect': typeof ApiIntegrationsGoogleDisconnectRoute
  '/api/integrations/google/start': typeof ApiIntegrationsGoogleStartRoute
  '/api/integrations/google/status': typeof ApiIntegrationsGoogleStatusRoute
  '/api/integrations/google/sync': typeof ApiIntegrationsGoogleSyncRoute
  '/api/integrations/meta/callback': typeof ApiIntegrationsMetaCallbackRoute
  '/api/integrations/meta/disconnect': typeof ApiIntegrationsMetaDisconnectRoute
  '/api/integrations/meta/media': typeof ApiIntegrationsMetaMediaRoute
  '/api/integrations/meta/start': typeof ApiIntegrationsMetaStartRoute
  '/api/integrations/meta/status': typeof ApiIntegrationsMetaStatusRoute
  '/api/integrations/meta/validate': typeof ApiIntegrationsMetaValidateRoute
  '/api/integrations/n8n/configure': typeof ApiIntegrationsN8nConfigureRoute
  '/api/integrations/n8n/disconnect': typeof ApiIntegrationsN8nDisconnectRoute
  '/api/integrations/n8n/events': typeof ApiIntegrationsN8nEventsRoute
  '/api/integrations/n8n/status': typeof ApiIntegrationsN8nStatusRoute
  '/api/integrations/n8n/test': typeof ApiIntegrationsN8nTestRoute
  '/api/public/bookings/$slug': typeof ApiPublicBookingsSlugRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/api/integrations/meta/whatsapp/complete': typeof ApiIntegrationsMetaWhatsappCompleteRoute
  '/api/integrations/meta/whatsapp/disconnect': typeof ApiIntegrationsMetaWhatsappDisconnectRoute
  '/api/integrations/meta/whatsapp/register': typeof ApiIntegrationsMetaWhatsappRegisterRoute
  '/api/integrations/meta/whatsapp/templates': typeof ApiIntegrationsMetaWhatsappTemplatesRoute
  '/api/integrations/meta/whatsapp/validate': typeof ApiIntegrationsMetaWhatsappValidateRoute
  '/api/public/webhooks/n8n/$connectionId': typeof ApiPublicWebhooksN8nConnectionIdRoute
  '/api/integrations/meta/whatsapp/media/$mediaId': typeof ApiIntegrationsMetaWhatsappMediaMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exclusao-de-dados'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/agentes'
    | '/auto-like'
    | '/calendario'
    | '/comment-to-dm'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/gatilhos'
    | '/inbox'
    | '/insights'
    | '/integracoes'
    | '/manual'
    | '/operacoes'
    | '/publicar'
    | '/reengajamento'
    | '/sequencias'
    | '/agendar/$slug'
    | '/api/auto-like'
    | '/api/automations'
    | '/api/calendar'
    | '/api/campaigns'
    | '/api/contact-tags'
    | '/api/contacts'
    | '/api/content'
    | '/api/dashboard'
    | '/api/data-deletion'
    | '/api/health'
    | '/api/inbox'
    | '/api/insights'
    | '/api/ready'
    | '/api/sequences'
    | '/api/triggers'
    | '/api/workspaces'
    | '/api/ai/agents'
    | '/api/ai/knowledge'
    | '/api/ai/settings'
    | '/api/ai/suggest'
    | '/api/automations/$flowId'
    | '/api/automations/fields'
    | '/api/calendar/booking-pages'
    | '/api/calendar/bookings'
    | '/api/compliance/check'
    | '/api/contacts/$contactId'
    | '/api/contacts/bulk'
    | '/api/messages/send'
    | '/api/operations/go-live'
    | '/api/operations/webhooks'
    | '/api/privacy/deletion-requests'
    | '/api/public/reviews'
    | '/api/automations/$flowId/execute'
    | '/api/automations/$flowId/simulate'
    | '/api/contacts/$contactId/notes'
    | '/api/integrations/google/callback'
    | '/api/integrations/google/disconnect'
    | '/api/integrations/google/start'
    | '/api/integrations/google/status'
    | '/api/integrations/google/sync'
    | '/api/integrations/meta/callback'
    | '/api/integrations/meta/disconnect'
    | '/api/integrations/meta/media'
    | '/api/integrations/meta/start'
    | '/api/integrations/meta/status'
    | '/api/integrations/meta/validate'
    | '/api/integrations/n8n/configure'
    | '/api/integrations/n8n/disconnect'
    | '/api/integrations/n8n/events'
    | '/api/integrations/n8n/status'
    | '/api/integrations/n8n/test'
    | '/api/public/bookings/$slug'
    | '/api/public/webhooks/instagram'
    | '/api/public/webhooks/whatsapp'
    | '/api/integrations/meta/whatsapp/complete'
    | '/api/integrations/meta/whatsapp/disconnect'
    | '/api/integrations/meta/whatsapp/register'
    | '/api/integrations/meta/whatsapp/templates'
    | '/api/integrations/meta/whatsapp/validate'
    | '/api/public/webhooks/n8n/$connectionId'
    | '/api/integrations/meta/whatsapp/media/$mediaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exclusao-de-dados'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/agentes'
    | '/auto-like'
    | '/calendario'
    | '/comment-to-dm'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/gatilhos'
    | '/inbox'
    | '/insights'
    | '/integracoes'
    | '/manual'
    | '/operacoes'
    | '/publicar'
    | '/reengajamento'
    | '/sequencias'
    | '/agendar/$slug'
    | '/api/auto-like'
    | '/api/automations'
    | '/api/calendar'
    | '/api/campaigns'
    | '/api/contact-tags'
    | '/api/contacts'
    | '/api/content'
    | '/api/dashboard'
    | '/api/data-deletion'
    | '/api/health'
    | '/api/inbox'
    | '/api/insights'
    | '/api/ready'
    | '/api/sequences'
    | '/api/triggers'
    | '/api/workspaces'
    | '/api/ai/agents'
    | '/api/ai/knowledge'
    | '/api/ai/settings'
    | '/api/ai/suggest'
    | '/api/automations/$flowId'
    | '/api/automations/fields'
    | '/api/calendar/booking-pages'
    | '/api/calendar/bookings'
    | '/api/compliance/check'
    | '/api/contacts/$contactId'
    | '/api/contacts/bulk'
    | '/api/messages/send'
    | '/api/operations/go-live'
    | '/api/operations/webhooks'
    | '/api/privacy/deletion-requests'
    | '/api/public/reviews'
    | '/api/automations/$flowId/execute'
    | '/api/automations/$flowId/simulate'
    | '/api/contacts/$contactId/notes'
    | '/api/integrations/google/callback'
    | '/api/integrations/google/disconnect'
    | '/api/integrations/google/start'
    | '/api/integrations/google/status'
    | '/api/integrations/google/sync'
    | '/api/integrations/meta/callback'
    | '/api/integrations/meta/disconnect'
    | '/api/integrations/meta/media'
    | '/api/integrations/meta/start'
    | '/api/integrations/meta/status'
    | '/api/integrations/meta/validate'
    | '/api/integrations/n8n/configure'
    | '/api/integrations/n8n/disconnect'
    | '/api/integrations/n8n/events'
    | '/api/integrations/n8n/status'
    | '/api/integrations/n8n/test'
    | '/api/public/bookings/$slug'
    | '/api/public/webhooks/instagram'
    | '/api/public/webhooks/whatsapp'
    | '/api/integrations/meta/whatsapp/complete'
    | '/api/integrations/meta/whatsapp/disconnect'
    | '/api/integrations/meta/whatsapp/register'
    | '/api/integrations/meta/whatsapp/templates'
    | '/api/integrations/meta/whatsapp/validate'
    | '/api/public/webhooks/n8n/$connectionId'
    | '/api/integrations/meta/whatsapp/media/$mediaId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/exclusao-de-dados'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/_app/agentes'
    | '/_app/auto-like'
    | '/_app/calendario'
    | '/_app/comment-to-dm'
    | '/_app/configuracoes'
    | '/_app/contatos'
    | '/_app/dashboard'
    | '/_app/gatilhos'
    | '/_app/inbox'
    | '/_app/insights'
    | '/_app/integracoes'
    | '/_app/manual'
    | '/_app/operacoes'
    | '/_app/publicar'
    | '/_app/reengajamento'
    | '/_app/sequencias'
    | '/agendar/$slug'
    | '/api/auto-like'
    | '/api/automations'
    | '/api/calendar'
    | '/api/campaigns'
    | '/api/contact-tags'
    | '/api/contacts'
    | '/api/content'
    | '/api/dashboard'
    | '/api/data-deletion'
    | '/api/health'
    | '/api/inbox'
    | '/api/insights'
    | '/api/ready'
    | '/api/sequences'
    | '/api/triggers'
    | '/api/workspaces'
    | '/api/ai/agents'
    | '/api/ai/knowledge'
    | '/api/ai/settings'
    | '/api/ai/suggest'
    | '/api/automations/$flowId'
    | '/api/automations/fields'
    | '/api/calendar/booking-pages'
    | '/api/calendar/bookings'
    | '/api/compliance/check'
    | '/api/contacts/$contactId'
    | '/api/contacts/bulk'
    | '/api/messages/send'
    | '/api/operations/go-live'
    | '/api/operations/webhooks'
    | '/api/privacy/deletion-requests'
    | '/api/public/reviews'
    | '/api/automations/$flowId/execute'
    | '/api/automations/$flowId/simulate'
    | '/api/contacts/$contactId/notes'
    | '/api/integrations/google/callback'
    | '/api/integrations/google/disconnect'
    | '/api/integrations/google/start'
    | '/api/integrations/google/status'
    | '/api/integrations/google/sync'
    | '/api/integrations/meta/callback'
    | '/api/integrations/meta/disconnect'
    | '/api/integrations/meta/media'
    | '/api/integrations/meta/start'
    | '/api/integrations/meta/status'
    | '/api/integrations/meta/validate'
    | '/api/integrations/n8n/configure'
    | '/api/integrations/n8n/disconnect'
    | '/api/integrations/n8n/events'
    | '/api/integrations/n8n/status'
    | '/api/integrations/n8n/test'
    | '/api/public/bookings/$slug'
    | '/api/public/webhooks/instagram'
    | '/api/public/webhooks/whatsapp'
    | '/api/integrations/meta/whatsapp/complete'
    | '/api/integrations/meta/whatsapp/disconnect'
    | '/api/integrations/meta/whatsapp/register'
    | '/api/integrations/meta/whatsapp/templates'
    | '/api/integrations/meta/whatsapp/validate'
    | '/api/public/webhooks/n8n/$connectionId'
    | '/api/integrations/meta/whatsapp/media/$mediaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ExclusaoDeDadosRoute: typeof ExclusaoDeDadosRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ApiAutoLikeRoute: typeof ApiAutoLikeRoute
  ApiAutomationsRoute: typeof ApiAutomationsRouteWithChildren
  ApiCalendarRoute: typeof ApiCalendarRouteWithChildren
  ApiCampaignsRoute: typeof ApiCampaignsRoute
  ApiContactTagsRoute: typeof ApiContactTagsRoute
  ApiContactsRoute: typeof ApiContactsRouteWithChildren
  ApiContentRoute: typeof ApiContentRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiDataDeletionRoute: typeof ApiDataDeletionRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInboxRoute: typeof ApiInboxRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiSequencesRoute: typeof ApiSequencesRoute
  ApiTriggersRoute: typeof ApiTriggersRoute
  ApiWorkspacesRoute: typeof ApiWorkspacesRoute
  ApiAiAgentsRoute: typeof ApiAiAgentsRoute
  ApiAiKnowledgeRoute: typeof ApiAiKnowledgeRoute
  ApiAiSettingsRoute: typeof ApiAiSettingsRoute
  ApiAiSuggestRoute: typeof ApiAiSuggestRoute
  ApiComplianceCheckRoute: typeof ApiComplianceCheckRoute
  ApiMessagesSendRoute: typeof ApiMessagesSendRoute
  ApiOperationsGoLiveRoute: typeof ApiOperationsGoLiveRoute
  ApiOperationsWebhooksRoute: typeof ApiOperationsWebhooksRoute
  ApiPrivacyDeletionRequestsRoute: typeof ApiPrivacyDeletionRequestsRoute
  ApiPublicReviewsRoute: typeof ApiPublicReviewsRoute
  ApiIntegrationsGoogleCallbackRoute: typeof ApiIntegrationsGoogleCallbackRoute
  ApiIntegrationsGoogleDisconnectRoute: typeof ApiIntegrationsGoogleDisconnectRoute
  ApiIntegrationsGoogleStartRoute: typeof ApiIntegrationsGoogleStartRoute
  ApiIntegrationsGoogleStatusRoute: typeof ApiIntegrationsGoogleStatusRoute
  ApiIntegrationsGoogleSyncRoute: typeof ApiIntegrationsGoogleSyncRoute
  ApiIntegrationsMetaCallbackRoute: typeof ApiIntegrationsMetaCallbackRoute
  ApiIntegrationsMetaDisconnectRoute: typeof ApiIntegrationsMetaDisconnectRoute
  ApiIntegrationsMetaMediaRoute: typeof ApiIntegrationsMetaMediaRoute
  ApiIntegrationsMetaStartRoute: typeof ApiIntegrationsMetaStartRoute
  ApiIntegrationsMetaStatusRoute: typeof ApiIntegrationsMetaStatusRoute
  ApiIntegrationsMetaValidateRoute: typeof ApiIntegrationsMetaValidateRoute
  ApiIntegrationsN8nConfigureRoute: typeof ApiIntegrationsN8nConfigureRoute
  ApiIntegrationsN8nDisconnectRoute: typeof ApiIntegrationsN8nDisconnectRoute
  ApiIntegrationsN8nEventsRoute: typeof ApiIntegrationsN8nEventsRoute
  ApiIntegrationsN8nStatusRoute: typeof ApiIntegrationsN8nStatusRoute
  ApiIntegrationsN8nTestRoute: typeof ApiIntegrationsN8nTestRoute
  ApiPublicBookingsSlugRoute: typeof ApiPublicBookingsSlugRoute
  ApiPublicWebhooksInstagramRoute: typeof ApiPublicWebhooksInstagramRoute
  ApiPublicWebhooksWhatsappRoute: typeof ApiPublicWebhooksWhatsappRoute
  ApiIntegrationsMetaWhatsappCompleteRoute: typeof ApiIntegrationsMetaWhatsappCompleteRoute
  ApiIntegrationsMetaWhatsappDisconnectRoute: typeof ApiIntegrationsMetaWhatsappDisconnectRoute
  ApiIntegrationsMetaWhatsappRegisterRoute: typeof ApiIntegrationsMetaWhatsappRegisterRoute
  ApiIntegrationsMetaWhatsappTemplatesRoute: typeof ApiIntegrationsMetaWhatsappTemplatesRoute
  ApiIntegrationsMetaWhatsappValidateRoute: typeof ApiIntegrationsMetaWhatsappValidateRoute
  ApiPublicWebhooksN8nConnectionIdRoute: typeof ApiPublicWebhooksN8nConnectionIdRoute
  ApiIntegrationsMetaWhatsappMediaMediaIdRoute: typeof ApiIntegrationsMetaWhatsappMediaMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-dados': {
      id: '/exclusao-de-dados'
      path: '/exclusao-de-dados'
      fullPath: '/exclusao-de-dados'
      preLoaderRoute: typeof ExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agentes': {
      id: '/_app/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AppAgentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auto-like': {
      id: '/_app/auto-like'
      path: '/auto-like'
      fullPath: '/auto-like'
      preLoaderRoute: typeof AppAutoLikeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comment-to-dm': {
      id: '/_app/comment-to-dm'
      path: '/comment-to-dm'
      fullPath: '/comment-to-dm'
      preLoaderRoute: typeof AppCommentToDmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatos': {
      id: '/_app/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gatilhos': {
      id: '/_app/gatilhos'
      path: '/gatilhos'
      fullPath: '/gatilhos'
      preLoaderRoute: typeof AppGatilhosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integracoes': {
      id: '/_app/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manual': {
      id: '/_app/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof AppManualRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operacoes': {
      id: '/_app/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof AppOperacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publicar': {
      id: '/_app/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof AppPublicarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reengajamento': {
      id: '/_app/reengajamento'
      path: '/reengajamento'
      fullPath: '/reengajamento'
      preLoaderRoute: typeof AppReengajamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sequencias': {
      id: '/_app/sequencias'
      path: '/sequencias'
      fullPath: '/sequencias'
      preLoaderRoute: typeof AppSequenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auto-like': {
      id: '/api/auto-like'
      path: '/api/auto-like'
      fullPath: '/api/auto-like'
      preLoaderRoute: typeof ApiAutoLikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automations': {
      id: '/api/automations'
      path: '/api/automations'
      fullPath: '/api/automations'
      preLoaderRoute: typeof ApiAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar': {
      id: '/api/calendar'
      path: '/api/calendar'
      fullPath: '/api/calendar'
      preLoaderRoute: typeof ApiCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact-tags': {
      id: '/api/contact-tags'
      path: '/api/contact-tags'
      fullPath: '/api/contact-tags'
      preLoaderRoute: typeof ApiContactTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts': {
      id: '/api/contacts'
      path: '/api/contacts'
      fullPath: '/api/contacts'
      preLoaderRoute: typeof ApiContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data-deletion': {
      id: '/api/data-deletion'
      path: '/api/data-deletion'
      fullPath: '/api/data-deletion'
      preLoaderRoute: typeof ApiDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sequences': {
      id: '/api/sequences'
      path: '/api/sequences'
      fullPath: '/api/sequences'
      preLoaderRoute: typeof ApiSequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/triggers': {
      id: '/api/triggers'
      path: '/api/triggers'
      fullPath: '/api/triggers'
      preLoaderRoute: typeof ApiTriggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces': {
      id: '/api/workspaces'
      path: '/api/workspaces'
      fullPath: '/api/workspaces'
      preLoaderRoute: typeof ApiWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/agents': {
      id: '/api/ai/agents'
      path: '/api/ai/agents'
      fullPath: '/api/ai/agents'
      preLoaderRoute: typeof ApiAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/knowledge': {
      id: '/api/ai/knowledge'
      path: '/api/ai/knowledge'
      fullPath: '/api/ai/knowledge'
      preLoaderRoute: typeof ApiAiKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/settings': {
      id: '/api/ai/settings'
      path: '/api/ai/settings'
      fullPath: '/api/ai/settings'
      preLoaderRoute: typeof ApiAiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/suggest': {
      id: '/api/ai/suggest'
      path: '/api/ai/suggest'
      fullPath: '/api/ai/suggest'
      preLoaderRoute: typeof ApiAiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automations/$flowId': {
      id: '/api/automations/$flowId'
      path: '/$flowId'
      fullPath: '/api/automations/$flowId'
      preLoaderRoute: typeof ApiAutomationsFlowIdRouteImport
      parentRoute: typeof ApiAutomationsRoute
    }
    '/api/automations/fields': {
      id: '/api/automations/fields'
      path: '/fields'
      fullPath: '/api/automations/fields'
      preLoaderRoute: typeof ApiAutomationsFieldsRouteImport
      parentRoute: typeof ApiAutomationsRoute
    }
    '/api/calendar/booking-pages': {
      id: '/api/calendar/booking-pages'
      path: '/booking-pages'
      fullPath: '/api/calendar/booking-pages'
      preLoaderRoute: typeof ApiCalendarBookingPagesRouteImport
      parentRoute: typeof ApiCalendarRoute
    }
    '/api/calendar/bookings': {
      id: '/api/calendar/bookings'
      path: '/bookings'
      fullPath: '/api/calendar/bookings'
      preLoaderRoute: typeof ApiCalendarBookingsRouteImport
      parentRoute: typeof ApiCalendarRoute
    }
    '/api/compliance/check': {
      id: '/api/compliance/check'
      path: '/api/compliance/check'
      fullPath: '/api/compliance/check'
      preLoaderRoute: typeof ApiComplianceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts/$contactId': {
      id: '/api/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/api/contacts/$contactId'
      preLoaderRoute: typeof ApiContactsContactIdRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/contacts/bulk': {
      id: '/api/contacts/bulk'
      path: '/bulk'
      fullPath: '/api/contacts/bulk'
      preLoaderRoute: typeof ApiContactsBulkRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/messages/send': {
      id: '/api/messages/send'
      path: '/api/messages/send'
      fullPath: '/api/messages/send'
      preLoaderRoute: typeof ApiMessagesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operations/go-live': {
      id: '/api/operations/go-live'
      path: '/api/operations/go-live'
      fullPath: '/api/operations/go-live'
      preLoaderRoute: typeof ApiOperationsGoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operations/webhooks': {
      id: '/api/operations/webhooks'
      path: '/api/operations/webhooks'
      fullPath: '/api/operations/webhooks'
      preLoaderRoute: typeof ApiOperationsWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/privacy/deletion-requests': {
      id: '/api/privacy/deletion-requests'
      path: '/api/privacy/deletion-requests'
      fullPath: '/api/privacy/deletion-requests'
      preLoaderRoute: typeof ApiPrivacyDeletionRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reviews': {
      id: '/api/public/reviews'
      path: '/api/public/reviews'
      fullPath: '/api/public/reviews'
      preLoaderRoute: typeof ApiPublicReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automations/$flowId/execute': {
      id: '/api/automations/$flowId/execute'
      path: '/execute'
      fullPath: '/api/automations/$flowId/execute'
      preLoaderRoute: typeof ApiAutomationsFlowIdExecuteRouteImport
      parentRoute: typeof ApiAutomationsFlowIdRoute
    }
    '/api/automations/$flowId/simulate': {
      id: '/api/automations/$flowId/simulate'
      path: '/simulate'
      fullPath: '/api/automations/$flowId/simulate'
      preLoaderRoute: typeof ApiAutomationsFlowIdSimulateRouteImport
      parentRoute: typeof ApiAutomationsFlowIdRoute
    }
    '/api/contacts/$contactId/notes': {
      id: '/api/contacts/$contactId/notes'
      path: '/notes'
      fullPath: '/api/contacts/$contactId/notes'
      preLoaderRoute: typeof ApiContactsContactIdNotesRouteImport
      parentRoute: typeof ApiContactsContactIdRoute
    }
    '/api/integrations/google/callback': {
      id: '/api/integrations/google/callback'
      path: '/api/integrations/google/callback'
      fullPath: '/api/integrations/google/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/disconnect': {
      id: '/api/integrations/google/disconnect'
      path: '/api/integrations/google/disconnect'
      fullPath: '/api/integrations/google/disconnect'
      preLoaderRoute: typeof ApiIntegrationsGoogleDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/start': {
      id: '/api/integrations/google/start'
      path: '/api/integrations/google/start'
      fullPath: '/api/integrations/google/start'
      preLoaderRoute: typeof ApiIntegrationsGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/status': {
      id: '/api/integrations/google/status'
      path: '/api/integrations/google/status'
      fullPath: '/api/integrations/google/status'
      preLoaderRoute: typeof ApiIntegrationsGoogleStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/sync': {
      id: '/api/integrations/google/sync'
      path: '/api/integrations/google/sync'
      fullPath: '/api/integrations/google/sync'
      preLoaderRoute: typeof ApiIntegrationsGoogleSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/callback': {
      id: '/api/integrations/meta/callback'
      path: '/api/integrations/meta/callback'
      fullPath: '/api/integrations/meta/callback'
      preLoaderRoute: typeof ApiIntegrationsMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/disconnect': {
      id: '/api/integrations/meta/disconnect'
      path: '/api/integrations/meta/disconnect'
      fullPath: '/api/integrations/meta/disconnect'
      preLoaderRoute: typeof ApiIntegrationsMetaDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/media': {
      id: '/api/integrations/meta/media'
      path: '/api/integrations/meta/media'
      fullPath: '/api/integrations/meta/media'
      preLoaderRoute: typeof ApiIntegrationsMetaMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/start': {
      id: '/api/integrations/meta/start'
      path: '/api/integrations/meta/start'
      fullPath: '/api/integrations/meta/start'
      preLoaderRoute: typeof ApiIntegrationsMetaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/status': {
      id: '/api/integrations/meta/status'
      path: '/api/integrations/meta/status'
      fullPath: '/api/integrations/meta/status'
      preLoaderRoute: typeof ApiIntegrationsMetaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/validate': {
      id: '/api/integrations/meta/validate'
      path: '/api/integrations/meta/validate'
      fullPath: '/api/integrations/meta/validate'
      preLoaderRoute: typeof ApiIntegrationsMetaValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/n8n/configure': {
      id: '/api/integrations/n8n/configure'
      path: '/api/integrations/n8n/configure'
      fullPath: '/api/integrations/n8n/configure'
      preLoaderRoute: typeof ApiIntegrationsN8nConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/n8n/disconnect': {
      id: '/api/integrations/n8n/disconnect'
      path: '/api/integrations/n8n/disconnect'
      fullPath: '/api/integrations/n8n/disconnect'
      preLoaderRoute: typeof ApiIntegrationsN8nDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/n8n/events': {
      id: '/api/integrations/n8n/events'
      path: '/api/integrations/n8n/events'
      fullPath: '/api/integrations/n8n/events'
      preLoaderRoute: typeof ApiIntegrationsN8nEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/n8n/status': {
      id: '/api/integrations/n8n/status'
      path: '/api/integrations/n8n/status'
      fullPath: '/api/integrations/n8n/status'
      preLoaderRoute: typeof ApiIntegrationsN8nStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/n8n/test': {
      id: '/api/integrations/n8n/test'
      path: '/api/integrations/n8n/test'
      fullPath: '/api/integrations/n8n/test'
      preLoaderRoute: typeof ApiIntegrationsN8nTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings/$slug': {
      id: '/api/public/bookings/$slug'
      path: '/api/public/bookings/$slug'
      fullPath: '/api/public/bookings/$slug'
      preLoaderRoute: typeof ApiPublicBookingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/instagram': {
      id: '/api/public/webhooks/instagram'
      path: '/api/public/webhooks/instagram'
      fullPath: '/api/public/webhooks/instagram'
      preLoaderRoute: typeof ApiPublicWebhooksInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp': {
      id: '/api/public/webhooks/whatsapp'
      path: '/api/public/webhooks/whatsapp'
      fullPath: '/api/public/webhooks/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/whatsapp/complete': {
      id: '/api/integrations/meta/whatsapp/complete'
      path: '/api/integrations/meta/whatsapp/complete'
      fullPath: '/api/integrations/meta/whatsapp/complete'
      preLoaderRoute: typeof ApiIntegrationsMetaWhatsappCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/whatsapp/disconnect': {
      id: '/api/integrations/meta/whatsapp/disconnect'
      path: '/api/integrations/meta/whatsapp/disconnect'
      fullPath: '/api/integrations/meta/whatsapp/disconnect'
      preLoaderRoute: typeof ApiIntegrationsMetaWhatsappDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/whatsapp/register': {
      id: '/api/integrations/meta/whatsapp/register'
      path: '/api/integrations/meta/whatsapp/register'
      fullPath: '/api/integrations/meta/whatsapp/register'
      preLoaderRoute: typeof ApiIntegrationsMetaWhatsappRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/whatsapp/templates': {
      id: '/api/integrations/meta/whatsapp/templates'
      path: '/api/integrations/meta/whatsapp/templates'
      fullPath: '/api/integrations/meta/whatsapp/templates'
      preLoaderRoute: typeof ApiIntegrationsMetaWhatsappTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/whatsapp/validate': {
      id: '/api/integrations/meta/whatsapp/validate'
      path: '/api/integrations/meta/whatsapp/validate'
      fullPath: '/api/integrations/meta/whatsapp/validate'
      preLoaderRoute: typeof ApiIntegrationsMetaWhatsappValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/n8n/$connectionId': {
      id: '/api/public/webhooks/n8n/$connectionId'
      path: '/api/public/webhooks/n8n/$connectionId'
      fullPath: '/api/public/webhooks/n8n/$connectionId'
      preLoaderRoute: typeof ApiPublicWebhooksN8nConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/meta/whatsapp/media/$mediaId': {
      id: '/api/integrations/meta/whatsapp/media/$mediaId'
      path: '/api/integrations/meta/whatsapp/media/$mediaId'
      fullPath: '/api/integrations/meta/whatsapp/media/$mediaId'
      preLoaderRoute: typeof ApiIntegrationsMetaWhatsappMediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgentesRoute: typeof AppAgentesRoute
  AppAutoLikeRoute: typeof AppAutoLikeRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppCommentToDmRoute: typeof AppCommentToDmRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContatosRoute: typeof AppContatosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGatilhosRoute: typeof AppGatilhosRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppManualRoute: typeof AppManualRoute
  AppOperacoesRoute: typeof AppOperacoesRoute
  AppPublicarRoute: typeof AppPublicarRoute
  AppReengajamentoRoute: typeof AppReengajamentoRoute
  AppSequenciasRoute: typeof AppSequenciasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentesRoute: AppAgentesRoute,
  AppAutoLikeRoute: AppAutoLikeRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppCommentToDmRoute: AppCommentToDmRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContatosRoute: AppContatosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGatilhosRoute: AppGatilhosRoute,
  AppInboxRoute: AppInboxRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppManualRoute: AppManualRoute,
  AppOperacoesRoute: AppOperacoesRoute,
  AppPublicarRoute: AppPublicarRoute,
  AppReengajamentoRoute: AppReengajamentoRoute,
  AppSequenciasRoute: AppSequenciasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAutomationsFlowIdRouteChildren {
  ApiAutomationsFlowIdExecuteRoute: typeof ApiAutomationsFlowIdExecuteRoute
  ApiAutomationsFlowIdSimulateRoute: typeof ApiAutomationsFlowIdSimulateRoute
}

const ApiAutomationsFlowIdRouteChildren: ApiAutomationsFlowIdRouteChildren = {
  ApiAutomationsFlowIdExecuteRoute: ApiAutomationsFlowIdExecuteRoute,
  ApiAutomationsFlowIdSimulateRoute: ApiAutomationsFlowIdSimulateRoute,
}

const ApiAutomationsFlowIdRouteWithChildren =
  ApiAutomationsFlowIdRoute._addFileChildren(ApiAutomationsFlowIdRouteChildren)

interface ApiAutomationsRouteChildren {
  ApiAutomationsFlowIdRoute: typeof ApiAutomationsFlowIdRouteWithChildren
  ApiAutomationsFieldsRoute: typeof ApiAutomationsFieldsRoute
}

const ApiAutomationsRouteChildren: ApiAutomationsRouteChildren = {
  ApiAutomationsFlowIdRoute: ApiAutomationsFlowIdRouteWithChildren,
  ApiAutomationsFieldsRoute: ApiAutomationsFieldsRoute,
}

const ApiAutomationsRouteWithChildren = ApiAutomationsRoute._addFileChildren(
  ApiAutomationsRouteChildren,
)

interface ApiCalendarRouteChildren {
  ApiCalendarBookingPagesRoute: typeof ApiCalendarBookingPagesRoute
  ApiCalendarBookingsRoute: typeof ApiCalendarBookingsRoute
}

const ApiCalendarRouteChildren: ApiCalendarRouteChildren = {
  ApiCalendarBookingPagesRoute: ApiCalendarBookingPagesRoute,
  ApiCalendarBookingsRoute: ApiCalendarBookingsRoute,
}

const ApiCalendarRouteWithChildren = ApiCalendarRoute._addFileChildren(
  ApiCalendarRouteChildren,
)

interface ApiContactsContactIdRouteChildren {
  ApiContactsContactIdNotesRoute: typeof ApiContactsContactIdNotesRoute
}

const ApiContactsContactIdRouteChildren: ApiContactsContactIdRouteChildren = {
  ApiContactsContactIdNotesRoute: ApiContactsContactIdNotesRoute,
}

const ApiContactsContactIdRouteWithChildren =
  ApiContactsContactIdRoute._addFileChildren(ApiContactsContactIdRouteChildren)

interface ApiContactsRouteChildren {
  ApiContactsContactIdRoute: typeof ApiContactsContactIdRouteWithChildren
  ApiContactsBulkRoute: typeof ApiContactsBulkRoute
}

const ApiContactsRouteChildren: ApiContactsRouteChildren = {
  ApiContactsContactIdRoute: ApiContactsContactIdRouteWithChildren,
  ApiContactsBulkRoute: ApiContactsBulkRoute,
}

const ApiContactsRouteWithChildren = ApiContactsRoute._addFileChildren(
  ApiContactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ExclusaoDeDadosRoute: ExclusaoDeDadosRoute,
  ObrigadoRoute: ObrigadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ApiAutoLikeRoute: ApiAutoLikeRoute,
  ApiAutomationsRoute: ApiAutomationsRouteWithChildren,
  ApiCalendarRoute: ApiCalendarRouteWithChildren,
  ApiCampaignsRoute: ApiCampaignsRoute,
  ApiContactTagsRoute: ApiContactTagsRoute,
  ApiContactsRoute: ApiContactsRouteWithChildren,
  ApiContentRoute: ApiContentRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiDataDeletionRoute: ApiDataDeletionRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInboxRoute: ApiInboxRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiSequencesRoute: ApiSequencesRoute,
  ApiTriggersRoute: ApiTriggersRoute,
  ApiWorkspacesRoute: ApiWorkspacesRoute,
  ApiAiAgentsRoute: ApiAiAgentsRoute,
  ApiAiKnowledgeRoute: ApiAiKnowledgeRoute,
  ApiAiSettingsRoute: ApiAiSettingsRoute,
  ApiAiSuggestRoute: ApiAiSuggestRoute,
  ApiComplianceCheckRoute: ApiComplianceCheckRoute,
  ApiMessagesSendRoute: ApiMessagesSendRoute,
  ApiOperationsGoLiveRoute: ApiOperationsGoLiveRoute,
  ApiOperationsWebhooksRoute: ApiOperationsWebhooksRoute,
  ApiPrivacyDeletionRequestsRoute: ApiPrivacyDeletionRequestsRoute,
  ApiPublicReviewsRoute: ApiPublicReviewsRoute,
  ApiIntegrationsGoogleCallbackRoute: ApiIntegrationsGoogleCallbackRoute,
  ApiIntegrationsGoogleDisconnectRoute: ApiIntegrationsGoogleDisconnectRoute,
  ApiIntegrationsGoogleStartRoute: ApiIntegrationsGoogleStartRoute,
  ApiIntegrationsGoogleStatusRoute: ApiIntegrationsGoogleStatusRoute,
  ApiIntegrationsGoogleSyncRoute: ApiIntegrationsGoogleSyncRoute,
  ApiIntegrationsMetaCallbackRoute: ApiIntegrationsMetaCallbackRoute,
  ApiIntegrationsMetaDisconnectRoute: ApiIntegrationsMetaDisconnectRoute,
  ApiIntegrationsMetaMediaRoute: ApiIntegrationsMetaMediaRoute,
  ApiIntegrationsMetaStartRoute: ApiIntegrationsMetaStartRoute,
  ApiIntegrationsMetaStatusRoute: ApiIntegrationsMetaStatusRoute,
  ApiIntegrationsMetaValidateRoute: ApiIntegrationsMetaValidateRoute,
  ApiIntegrationsN8nConfigureRoute: ApiIntegrationsN8nConfigureRoute,
  ApiIntegrationsN8nDisconnectRoute: ApiIntegrationsN8nDisconnectRoute,
  ApiIntegrationsN8nEventsRoute: ApiIntegrationsN8nEventsRoute,
  ApiIntegrationsN8nStatusRoute: ApiIntegrationsN8nStatusRoute,
  ApiIntegrationsN8nTestRoute: ApiIntegrationsN8nTestRoute,
  ApiPublicBookingsSlugRoute: ApiPublicBookingsSlugRoute,
  ApiPublicWebhooksInstagramRoute: ApiPublicWebhooksInstagramRoute,
  ApiPublicWebhooksWhatsappRoute: ApiPublicWebhooksWhatsappRoute,
  ApiIntegrationsMetaWhatsappCompleteRoute:
    ApiIntegrationsMetaWhatsappCompleteRoute,
  ApiIntegrationsMetaWhatsappDisconnectRoute:
    ApiIntegrationsMetaWhatsappDisconnectRoute,
  ApiIntegrationsMetaWhatsappRegisterRoute:
    ApiIntegrationsMetaWhatsappRegisterRoute,
  ApiIntegrationsMetaWhatsappTemplatesRoute:
    ApiIntegrationsMetaWhatsappTemplatesRoute,
  ApiIntegrationsMetaWhatsappValidateRoute:
    ApiIntegrationsMetaWhatsappValidateRoute,
  ApiPublicWebhooksN8nConnectionIdRoute: ApiPublicWebhooksN8nConnectionIdRoute,
  ApiIntegrationsMetaWhatsappMediaMediaIdRoute:
    ApiIntegrationsMetaWhatsappMediaMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
