/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ExclusaoDeDadosRouteImport } from './routes/exclusao-de-dados'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AppAgentesRouteImport } from './routes/_app/agentes'
import { Route as AppAutoLikeRouteImport } from './routes/_app/auto-like'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppContatosRouteImport } from './routes/_app/contatos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppGatilhosRouteImport } from './routes/_app/gatilhos'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppPublicarRouteImport } from './routes/_app/publicar'
import { Route as AppReengajamentoRouteImport } from './routes/_app/reengajamento'
import { Route as AppSequenciasRouteImport } from './routes/_app/sequencias'
import { Route as ApiDataDeletionRouteImport } from './routes/api/data-deletion'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAiSuggestRouteImport } from './routes/api/ai/suggest'
import { Route as ApiComplianceCheckRouteImport } from './routes/api/compliance/check'
import { Route as ApiPublicWebhooksInstagramRouteImport } from './routes/api/public/webhooks/instagram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeDadosRoute = ExclusaoDeDadosRouteImport.update({
  id: '/exclusao-de-dados',
  path: '/exclusao-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentesRoute = AppAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AppRoute,
} as any)
const AppAutoLikeRoute = AppAutoLikeRouteImport.update({
  id: '/auto-like',
  path: '/auto-like',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGatilhosRoute = AppGatilhosRouteImport.update({
  id: '/gatilhos',
  path: '/gatilhos',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicarRoute = AppPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => AppRoute,
} as any)
const AppReengajamentoRoute = AppReengajamentoRouteImport.update({
  id: '/reengajamento',
  path: '/reengajamento',
  getParentRoute: () => AppRoute,
} as any)
const AppSequenciasRoute = AppSequenciasRouteImport.update({
  id: '/sequencias',
  path: '/sequencias',
  getParentRoute: () => AppRoute,
} as any)
const ApiDataDeletionRoute = ApiDataDeletionRouteImport.update({
  id: '/api/data-deletion',
  path: '/api/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSuggestRoute = ApiAiSuggestRouteImport.update({
  id: '/api/ai/suggest',
  path: '/api/ai/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplianceCheckRoute = ApiComplianceCheckRouteImport.update({
  id: '/api/compliance/check',
  path: '/api/compliance/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksInstagramRoute =
  ApiPublicWebhooksInstagramRouteImport.update({
    id: '/api/public/webhooks/instagram',
    path: '/api/public/webhooks/instagram',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agentes': typeof AppAgentesRoute
  '/auto-like': typeof AppAutoLikeRoute
  '/calendario': typeof AppCalendarioRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/gatilhos': typeof AppGatilhosRoute
  '/inbox': typeof AppInboxRoute
  '/insights': typeof AppInsightsRoute
  '/publicar': typeof AppPublicarRoute
  '/reengajamento': typeof AppReengajamentoRoute
  '/sequencias': typeof AppSequenciasRoute
  '/api/data-deletion': typeof ApiDataDeletionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/compliance/check': typeof ApiComplianceCheckRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agentes': typeof AppAgentesRoute
  '/auto-like': typeof AppAutoLikeRoute
  '/calendario': typeof AppCalendarioRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/gatilhos': typeof AppGatilhosRoute
  '/inbox': typeof AppInboxRoute
  '/insights': typeof AppInsightsRoute
  '/publicar': typeof AppPublicarRoute
  '/reengajamento': typeof AppReengajamentoRoute
  '/sequencias': typeof AppSequenciasRoute
  '/api/data-deletion': typeof ApiDataDeletionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/compliance/check': typeof ApiComplianceCheckRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_app/agentes': typeof AppAgentesRoute
  '/_app/auto-like': typeof AppAutoLikeRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contatos': typeof AppContatosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gatilhos': typeof AppGatilhosRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/publicar': typeof AppPublicarRoute
  '/_app/reengajamento': typeof AppReengajamentoRoute
  '/_app/sequencias': typeof AppSequenciasRoute
  '/api/data-deletion': typeof ApiDataDeletionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/compliance/check': typeof ApiComplianceCheckRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exclusao-de-dados'
    | '/privacidade'
    | '/termos'
    | '/agentes'
    | '/auto-like'
    | '/calendario'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/gatilhos'
    | '/inbox'
    | '/insights'
    | '/publicar'
    | '/reengajamento'
    | '/sequencias'
    | '/api/data-deletion'
    | '/api/health'
    | '/api/ai/suggest'
    | '/api/compliance/check'
    | '/api/public/webhooks/instagram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exclusao-de-dados'
    | '/privacidade'
    | '/termos'
    | '/agentes'
    | '/auto-like'
    | '/calendario'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/gatilhos'
    | '/inbox'
    | '/insights'
    | '/publicar'
    | '/reengajamento'
    | '/sequencias'
    | '/api/data-deletion'
    | '/api/health'
    | '/api/ai/suggest'
    | '/api/compliance/check'
    | '/api/public/webhooks/instagram'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/exclusao-de-dados'
    | '/privacidade'
    | '/termos'
    | '/_app/agentes'
    | '/_app/auto-like'
    | '/_app/calendario'
    | '/_app/configuracoes'
    | '/_app/contatos'
    | '/_app/dashboard'
    | '/_app/gatilhos'
    | '/_app/inbox'
    | '/_app/insights'
    | '/_app/publicar'
    | '/_app/reengajamento'
    | '/_app/sequencias'
    | '/api/data-deletion'
    | '/api/health'
    | '/api/ai/suggest'
    | '/api/compliance/check'
    | '/api/public/webhooks/instagram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ExclusaoDeDadosRoute: typeof ExclusaoDeDadosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiDataDeletionRoute: typeof ApiDataDeletionRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAiSuggestRoute: typeof ApiAiSuggestRoute
  ApiComplianceCheckRoute: typeof ApiComplianceCheckRoute
  ApiPublicWebhooksInstagramRoute: typeof ApiPublicWebhooksInstagramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-dados': {
      id: '/exclusao-de-dados'
      path: '/exclusao-de-dados'
      fullPath: '/exclusao-de-dados'
      preLoaderRoute: typeof ExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agentes': {
      id: '/_app/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AppAgentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auto-like': {
      id: '/_app/auto-like'
      path: '/auto-like'
      fullPath: '/auto-like'
      preLoaderRoute: typeof AppAutoLikeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatos': {
      id: '/_app/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gatilhos': {
      id: '/_app/gatilhos'
      path: '/gatilhos'
      fullPath: '/gatilhos'
      preLoaderRoute: typeof AppGatilhosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publicar': {
      id: '/_app/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof AppPublicarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reengajamento': {
      id: '/_app/reengajamento'
      path: '/reengajamento'
      fullPath: '/reengajamento'
      preLoaderRoute: typeof AppReengajamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sequencias': {
      id: '/_app/sequencias'
      path: '/sequencias'
      fullPath: '/sequencias'
      preLoaderRoute: typeof AppSequenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/data-deletion': {
      id: '/api/data-deletion'
      path: '/api/data-deletion'
      fullPath: '/api/data-deletion'
      preLoaderRoute: typeof ApiDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/suggest': {
      id: '/api/ai/suggest'
      path: '/api/ai/suggest'
      fullPath: '/api/ai/suggest'
      preLoaderRoute: typeof ApiAiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compliance/check': {
      id: '/api/compliance/check'
      path: '/api/compliance/check'
      fullPath: '/api/compliance/check'
      preLoaderRoute: typeof ApiComplianceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/instagram': {
      id: '/api/public/webhooks/instagram'
      path: '/api/public/webhooks/instagram'
      fullPath: '/api/public/webhooks/instagram'
      preLoaderRoute: typeof ApiPublicWebhooksInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgentesRoute: typeof AppAgentesRoute
  AppAutoLikeRoute: typeof AppAutoLikeRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContatosRoute: typeof AppContatosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGatilhosRoute: typeof AppGatilhosRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppPublicarRoute: typeof AppPublicarRoute
  AppReengajamentoRoute: typeof AppReengajamentoRoute
  AppSequenciasRoute: typeof AppSequenciasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentesRoute: AppAgentesRoute,
  AppAutoLikeRoute: AppAutoLikeRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContatosRoute: AppContatosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGatilhosRoute: AppGatilhosRoute,
  AppInboxRoute: AppInboxRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppPublicarRoute: AppPublicarRoute,
  AppReengajamentoRoute: AppReengajamentoRoute,
  AppSequenciasRoute: AppSequenciasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ExclusaoDeDadosRoute: ExclusaoDeDadosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiDataDeletionRoute: ApiDataDeletionRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAiSuggestRoute: ApiAiSuggestRoute,
  ApiComplianceCheckRoute: ApiComplianceCheckRoute,
  ApiPublicWebhooksInstagramRoute: ApiPublicWebhooksInstagramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
