-- Wal Chat — conexões reais Meta/OpenAI e credenciais por tenant.
-- Secrets continuam cifrados pela aplicação e estas tabelas não são acessíveis
-- pelos papéis anon/authenticated, mesmo quando o schema public é exposto.

alter type public.window_policy add value if not exists 'private_reply_7d';

alter table public.instagram_accounts
  add column if not exists account_type text,
  add column if not exists connected_by uuid references auth.users(id) on delete set null,
  add column if not exists subscribed_fields text[] not null default '{}',
  add column if not exists permissions_validated_at timestamptz,
  add column if not exists token_refresh_after timestamptz,
  add column if not exists last_token_refresh_at timestamptz,
  add column if not exists last_sync_at timestamptz,
  add column if not exists connection_error text;

alter table public.instagram_accounts
  drop constraint if exists instagram_accounts_account_type_check;

alter table public.instagram_accounts
  add constraint instagram_accounts_account_type_check
  check (account_type is null or account_type in ('BUSINESS', 'CREATOR'));

create table public.integration_credentials (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  instagram_account_id uuid references public.instagram_accounts(id) on delete cascade,
  provider text not null check (provider in ('meta', 'openai', 'google')),
  credential_type text not null check (credential_type in ('access_token', 'api_key')),
  scope_key text not null,
  encrypted_value text not null,
  expires_at timestamptz,
  last_refreshed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (workspace_id, provider, credential_type, scope_key)
);

create table public.integration_oauth_states (
  state_hash text primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check (provider = 'meta'),
  redirect_after text not null default '/configuracoes',
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table public.ai_provider_settings (
  workspace_id uuid primary key references public.workspaces(id) on delete cascade,
  provider text not null default 'openai' check (provider in ('openai', 'google')),
  model text not null default 'gpt-5.6-sol',
  reasoning_effort text not null default 'low' check (reasoning_effort in ('none', 'low', 'medium', 'high')),
  response_verbosity text not null default 'low' check (response_verbosity in ('low', 'medium', 'high')),
  max_output_tokens integer not null default 500 check (max_output_tokens between 100 and 2000),
  is_enabled boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.ai_agents
  add column if not exists provider_override text,
  add column if not exists model_override text,
  add column if not exists max_reply_chars integer not null default 500,
  add column if not exists fallback_to_copilot boolean not null default true;

alter table public.ai_agents
  drop constraint if exists ai_agents_provider_override_check,
  drop constraint if exists ai_agents_max_reply_chars_check;

alter table public.ai_agents
  add constraint ai_agents_provider_override_check
    check (provider_override is null or provider_override in ('openai', 'google')),
  add constraint ai_agents_max_reply_chars_check
    check (max_reply_chars between 100 and 1000);

alter table public.comment_private_replies
  add column if not exists job_id uuid references public.scheduled_jobs(id) on delete set null,
  add column if not exists status text not null default 'pending',
  add column if not exists last_error text,
  alter column replied_at drop not null,
  alter column replied_at drop default;

alter table public.comment_private_replies
  drop constraint if exists comment_private_replies_status_check;

alter table public.comment_private_replies
  add constraint comment_private_replies_status_check
  check (status in ('pending', 'sent', 'failed'));

update public.comment_private_replies
set status = 'sent'
where replied_at is not null;

create table public.integration_audit_logs (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  provider text not null,
  action text not null,
  status text not null check (status in ('success', 'failure')),
  resource_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists integration_credentials_account_idx
  on public.integration_credentials (instagram_account_id)
  where instagram_account_id is not null;

create index if not exists integration_oauth_states_expiry_idx
  on public.integration_oauth_states (expires_at)
  where used_at is null;

create index if not exists integration_audit_workspace_created_idx
  on public.integration_audit_logs (workspace_id, created_at desc);

create unique index if not exists messages_interaction_unique_idx
  on public.messages (interaction_id);

alter table public.integration_credentials enable row level security;
alter table public.integration_oauth_states enable row level security;
alter table public.ai_provider_settings enable row level security;
alter table public.integration_audit_logs enable row level security;

create policy ai_provider_settings_select on public.ai_provider_settings
  for select to authenticated
  using (public.is_workspace_member(workspace_id));

create policy ai_provider_settings_insert on public.ai_provider_settings
  for insert to authenticated
  with check (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]));

create policy ai_provider_settings_update on public.ai_provider_settings
  for update to authenticated
  using (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]))
  with check (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]));

create policy integration_audit_select on public.integration_audit_logs
  for select to authenticated
  using (public.is_workspace_member(workspace_id));

-- As telas novas usam APIs server-side; impedir que viewer/agent contorne o
-- RBAC escrevendo diretamente nas tabelas pelo cliente Supabase.
drop policy if exists tenant_insert on public.instagram_accounts;
drop policy if exists tenant_update on public.instagram_accounts;
drop policy if exists tenant_delete on public.instagram_accounts;
create policy instagram_accounts_manage on public.instagram_accounts
  for all to authenticated
  using (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]))
  with check (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]));

drop policy if exists tenant_insert on public.ai_agents;
drop policy if exists tenant_update on public.ai_agents;
drop policy if exists tenant_delete on public.ai_agents;
create policy ai_agents_manage on public.ai_agents
  for all to authenticated
  using (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]))
  with check (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]));

drop policy if exists tenant_insert on public.knowledge_documents;
drop policy if exists tenant_update on public.knowledge_documents;
drop policy if exists tenant_delete on public.knowledge_documents;
create policy knowledge_documents_manage on public.knowledge_documents
  for all to authenticated
  using (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]))
  with check (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]));

drop policy if exists tenant_insert on public.triggers;
drop policy if exists tenant_update on public.triggers;
drop policy if exists tenant_delete on public.triggers;
create policy triggers_manage on public.triggers
  for all to authenticated
  using (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]))
  with check (public.has_workspace_role(workspace_id, array['owner','admin']::public.workspace_role[]));

create trigger set_integration_credentials_updated_at
  before update on public.integration_credentials
  for each row execute procedure public.set_updated_at();

create trigger set_ai_provider_settings_updated_at
  before update on public.ai_provider_settings
  for each row execute procedure public.set_updated_at();

-- O backend com service_role é o único leitor/escritor de credenciais e states.
revoke all on public.integration_credentials from anon, authenticated;
revoke all on public.integration_oauth_states from anon, authenticated;
revoke all on public.integration_audit_logs from anon, authenticated;
grant select on public.integration_audit_logs to authenticated;
grant all on public.integration_credentials to service_role;
grant all on public.integration_oauth_states to service_role;
grant all on public.ai_provider_settings to service_role;
grant all on public.integration_audit_logs to service_role;
grant usage, select on sequence public.integration_audit_logs_id_seq to service_role;

comment on table public.integration_credentials is
  'Secrets cifrados por workspace; somente service_role pode acessar.';
comment on table public.integration_oauth_states is
  'States OAuth de uso único e curta duração para impedir CSRF e replay.';
comment on table public.ai_provider_settings is
  'Provedor e modelo de IA por workspace; chaves ficam em integration_credentials.';
